export const content = {
  es: {
    tags: [
      [
        "JAVASCRIPT / TYPESCRIPT",
        "REACT",
        "NEXTJS",
        "NODEJS",
        "MYSQL",
        "TAILWIND",
        "AWS",
        "LINUX",
      ],
      [
        "FIGMA / ADOBE XD",
        "CSS / SASS / POSTCSS",
        "WEBPACK / GRUNT",
        "BOOTSTRAP",
        "HANDLEBARS",
        "PHP 7",
      ],
      [
        "GIT",
        "PROGRAMACIÓN FUNCIONAL",
        "PRINCIPIOS SOLID",
        "PROGRAMACIÓN ORIENTADA A OBJETOS",
        "DOCKER",
        "ASTRO",
      ],
    ],
  },
  en: {
    tags: [
      [
        "JAVASCRIPT / TYPESCRIPT",
        "REACT",
        "NEXTJS",
        "NODEJS",
        "MYSQL",
        "TAILWIND",
        "AWS",
        "LINUX",
      ],
      [
        "FIGMA / ADOBE XD",
        "CSS / SASS / POSTCSS",
        "WEBPACK / GRUNT",
        "BOOTSTRAP",
        "HANDLEBARS",
        "PHP 7",
      ],
      [
        "GIT",
        "FUNCTIONAL PROGRAMMING",
        "SOLID PRINCIPLES",
        "OBJECT-ORIENTED PROGRAMMING",
        "DOCKER",
        "ASTRO",
      ],
    ],
  },
  fr: {
    tags: [
      [
        "JAVASCRIPT / TYPESCRIPT",
        "REACT",
        "NEXTJS",
        "NODEJS",
        "MYSQL",
        "TAILWIND",
        "AWS",
        "LINUX",
      ],
      [
        "FIGMA / ADOBE XD",
        "CSS / SASS / POSTCSS",
        "WEBPACK / GRUNT",
        "BOOTSTRAP",
        "HANDLEBARS",
        "PHP 7",
      ],
      [
        "GIT",
        "PROGRAMMATION FONCTIONNELLE",
        "PRINCIPES SOLID",
        "PROGRAMMATION ORIENTÉE OBJET",
        "DOCKER",
        "ASTRO",
      ],
    ],
  },
};
